standalone vs embedded (#3)
* standalone vs embedded
This PR converts the exporter to a dual mode binary

The previous behaviour is preserved when run with a new argument
`embedded`which reads from stdin to track metrics.

The new mode `standalone` runs external to exabgp and leverages
`exabgpcli` to accomplish scraping.

Due to the differing levels of information available via exabgpcli, the
labels changed a bit so they were unified between modes.

Additionally, the metrics were converted to a more standard prometheus
model with a naming consistent with official exporters.

* fix pre-4.0.8 reporting of up/down
* update summary regexp

on long running instances, the format is slightly changed in the output
to better handle that, we're going to match the state string explicitly
based on the data here:
https://github.com/Exa-Networks/exabgp/blob/4ac33b99c646c36a63503295aac1d3e9e3129945/lib/exabgp/bgp/fsm.py#L30-L37

diff --git a/script/test-integration-local b/script/test-integration-local
--- a/script/test-integration-local
+++ b/script/test-integration-local
@@ -19,10 +19,11 @@ for v in 4 5 6 8 9 10; do
 		script/stop-docker
 		continue
 	fi
+	docker logs exabgp_exporter > /tmp/exabgp_export_docker_4_0_$v.log
 	script/stop-docker
 done
 
-echo "testing exabgp git master"
-EXABGP_VERSION=master script/run-docker
-test/libs/bats/bin/bats -t test/*.bats || echo "exabgp git test failed"
-script/stop-docker
+#echo "testing exabgp git master"
+#EXABGP_VERSION=master script/run-docker
+#test/libs/bats/bin/bats -t test/*.bats || echo "exabgp git test failed"
+#script/stop-docker
